export const KNOWLEDGE_NODES = [
  { code: "basic", name: "基础能力", cspImportance: 5 },
  { code: "greedy", name: "贪心", cspImportance: 5 },
  { code: "binary_search", name: "二分", cspImportance: 5 },
  { code: "data_structure", name: "数据结构", cspImportance: 5 },
  { code: "dp", name: "动态规划", cspImportance: 5 },
  { code: "graph", name: "图论", cspImportance: 5 },
  { code: "math", name: "数学", cspImportance: 4 },
  { code: "search", name: "搜索", cspImportance: 4 },
  { code: "string", name: "字符串", cspImportance: 3 },
  { parent: "basic", code: "implementation", name: "模拟与实现", cspImportance: 5 },
  { parent: "basic", code: "prefix_sum", name: "前缀和", cspImportance: 5 },
  { parent: "basic", code: "difference", name: "差分", cspImportance: 4 },
  { parent: "data_structure", code: "stack_queue", name: "栈与队列", cspImportance: 4 },
  { parent: "data_structure", code: "monotonic_stack_queue", name: "单调栈/单调队列", cspImportance: 4 },
  { parent: "data_structure", code: "heap", name: "堆/优先队列", cspImportance: 4 },
  { parent: "data_structure", code: "dsu", name: "并查集", cspImportance: 5 },
  { parent: "data_structure", code: "fenwick", name: "树状数组", cspImportance: 4 },
  { parent: "data_structure", code: "segment_tree", name: "线段树", cspImportance: 5 },
  { parent: "data_structure", code: "lca", name: "LCA", cspImportance: 4 },
  { parent: "dp", code: "linear_dp", name: "线性 DP", cspImportance: 5 },
  { parent: "dp", code: "knapsack_dp", name: "背包 DP", cspImportance: 5 },
  { parent: "dp", code: "interval_dp", name: "区间 DP", cspImportance: 5 },
  { parent: "dp", code: "tree_dp", name: "树形 DP", cspImportance: 5 },
  { parent: "dp", code: "state_compression_dp", name: "状压 DP", cspImportance: 4 },
  { parent: "dp", code: "dp_optimization", name: "DP 优化", cspImportance: 4 },
  { parent: "graph", code: "bfs_dfs_graph", name: "图上 DFS/BFS", cspImportance: 5 },
  { parent: "graph", code: "shortest_path", name: "最短路", cspImportance: 5 },
  { parent: "graph", code: "mst", name: "最小生成树", cspImportance: 4 },
  { parent: "graph", code: "toposort", name: "拓扑排序", cspImportance: 4 },
  { parent: "graph", code: "scc", name: "强连通分量", cspImportance: 3 },
  { parent: "graph", code: "tarjan", name: "Tarjan", cspImportance: 3 },
  { parent: "math", code: "number_theory", name: "数论", cspImportance: 4 },
  { parent: "math", code: "combinatorics", name: "组合数学", cspImportance: 4 },
  { parent: "search", code: "dfs_bfs", name: "DFS/BFS", cspImportance: 5 },
  { parent: "search", code: "pruning", name: "剪枝", cspImportance: 4 },
  { parent: "search", code: "memorized_search", name: "记忆化搜索", cspImportance: 4 },
  { parent: "string", code: "kmp", name: "KMP", cspImportance: 3 },
  { parent: "string", code: "trie", name: "Trie", cspImportance: 3 },
  { parent: "string", code: "hash", name: "字符串 Hash", cspImportance: 3 }
];
