export const assetIcons = {
  // Brand / people
  brandRobot: "/icons/icon-021.png",
  brandRobotAlt: "/icons/icon-113.png",
  brandOwl: "/icons/icon-088.png",
  brandOwlPointer: "/icons/icon-068.png",
  mascotToday: "/icons/icon-077.png",
  mascotAnalysis: "/icons/icon-037.png",
  mascotResult: "/icons/icon-111.png",
  mascotClipboard: "/icons/icon-112.png",
  mascotKey: "/icons/icon-088.png",
  userAvatar: "/icons/icon-023.png",

  // Navigation
  dashboard: "/icons/icon-051.png",
  home: "/icons/icon-090.png",
  today: "/icons/icon-052.png",
  calendar: "/icons/icon-053.png",
  review: "/icons/icon-054.png",
  report: "/icons/icon-005.png",
  settings: "/icons/icon-055.png",
  ability: "/icons/icon-129.png",
  sync: "/icons/icon-042.png",

  // Main concept icons
  target: "/icons/icon-001.png",
  targetBlue: "/icons/icon-098.png",
  clipboard: "/icons/icon-003.png",
  clipboardList: "/icons/icon-075.png",
  clipboardChart: "/icons/icon-087.png",
  chart: "/icons/icon-004.png",
  chartUp: "/icons/icon-040.png",
  chartBars: "/icons/icon-051.png",
  chartBarsPlain: "/icons/icon-129.png",
  code: "/icons/icon-010.png",
  codeSquare: "/icons/icon-116.png",
  codeMini: "/icons/icon-131.png",
  book: "/icons/icon-124.png",
  gift: "/icons/icon-123.png",
  lock: "/icons/icon-123.png",
  search: "/icons/icon-041.png",
  upload: "/icons/icon-047.png",
  file: "/icons/icon-093.png",
  filePurple: "/icons/icon-115.png",
  pdf: "/icons/icon-110.png",
  brain: "/icons/icon-099.png",
  users: "/icons/icon-097.png",
  graduation: "/icons/icon-012.png",
  planet: "/icons/icon-020.png",
  planetFaded: "/icons/icon-032.png",
  star: "/icons/icon-046.png",
  starOrange: "/icons/icon-120.png",
  shield: "/icons/icon-096.png",
  shieldHeart: "/icons/icon-015.png",
  shieldReport: "/icons/icon-016.png",
  zap: "/icons/icon-018.png",
  light: "/icons/icon-121.png",
  sparkle: "/icons/icon-069.png",
  sparkleSmall: "/icons/icon-069.png",

  // Status / action
  check: "/icons/icon-028.png",
  checkGreen: "/icons/icon-029.png",
  checkRound: "/icons/icon-045.png",
  checkPurple: "/icons/icon-094.png",
  checkGlass: "/icons/icon-106.png",
  warning: "/icons/icon-109.png",
  refresh: "/icons/icon-107.png",
  arrowRight: "/icons/icon-067.png",
  arrowRightBig: "/icons/icon-078.png",
  arrowUp: "/icons/icon-108.png",
  chevronRight: "/icons/icon-062.png",
  chevronRightThin: "/icons/icon-070.png",
  chevronDown: "/icons/icon-060.png",
  chevronLeft: "/icons/icon-061.png",
  clock: "/icons/icon-026.png",
  clockPurple: "/icons/icon-048.png",
  dot: "/icons/icon-063.png",
  dotGreen: "/icons/icon-064.png",
  circleTarget: "/icons/icon-065.png",
  loading: "/icons/icon-030.png",
  day26: "/icons/icon-079.png",

  // Decorative cards
  fadedChart: "/icons/icon-030.png",
  fadedCheck: "/icons/icon-031.png",
  fadedCode: "/icons/icon-033.png",
  fadedLight: "/icons/icon-034.png",
  cardDoc: "/icons/icon-076.png",
} as const;

export type AssetIconName = keyof typeof assetIcons;

export function asset(name: AssetIconName) {
  return assetIcons[name];
}
